
GET http://localhost:8081/contacts
Content-Type: application/json


### Agregar un nuevo contacto
POST http://localhost:8081/contacts
Content-Type: application/json

{
  "firstName": "Carla",
  "lastName": "Martínez",
  "email": "carla@example.com",
  "favoriteColor": "verde",
  "birthday": "1990-07-12"
}
